// frontend-svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { fade, fly, scale } from "svelte/transition";
  import { flip } from "svelte/animate";

  let summaryStatus: "none" | "loading" | "done" = "none";
  let summary = "";

  let search = "";
  let isSearchLoading = false;
  let currName = "";
  let currCase = "";

  let currentPhone;

  let timeout = null;

  $: currentPhone, fetchSummary();
  $: console.log(headings);

  const formatPhoneNumber = (phone) => {
    let formatted = "";
    for (let i = 0; i < phone.length; i++) {
      if (phone[i].match(/\d/)) {
        formatted += phone[i];
      }
    }
    return formatted;
  };

  const fetchSummary = () => {
    if (!currentPhone) return;
    summaryStatus = "loading";
    fetch(`http://localhost:8081/client/findByPhoneNumber`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        phone_number: currentPhone,
      }),
    })
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        summary = data?.[0]?.summary ?? "";
        summaryStatus = "done";
      })
      .catch(err => {
        console.log(err);
        summaryStatus = "done";
      });
  };

  interface Heading {
    name?: string;
    phone?: string;
    id: number;
    date: string;
  }
  let headings: Heading[] = [];
  const unshiftHeading = (heading: Heading) => {
    headings.unshift(heading);
    headings = headings;
    localStorage.setItem("headings", JSON.stringify(headings));
  };

  interface SearchResults {
    filename: string;
    summary: string;
    link: string;
  }
  let searchResults: SearchResults[] = [];

  onMount(() => {
    headings = JSON.parse(localStorage.getItem("headings")) || [];
    let socket = new WebSocket("ws://localhost:1234");
    socket.addEventListener("open", () => {
      console.log("WebSocket connected");
    });
    socket.addEventListener("error", (event) => {
      console.log("WebSocket error: ", event);
      console.log("Attempting to reconnect...");
      setTimeout(() => {
        socket = new WebSocket("ws://localhost:1234");
      }, 2000);
    });
    socket.addEventListener("message", (event) => {
      let data;
      try {
        data = JSON.parse(event.data);
      } catch (e) {
        return;
      }
      console.log(data);
      switch (data.type) {
        case "newphonecall":
          new Notification(`Incoming phone call`, {
            body: data.phone,
          });
          unshiftHeading({ phone: data.phone, id: Math.random(), date: new Date().toLocaleString() });
          currentPhone = formatPhoneNumber(data.phone);
          break;
        case "summary":
          summary = data.summary;
          summaryStatus = "done";
          break;
        case "name":
          headings.at(-1).name = data.name;
          summaryStatus = "done";
          break;
        case "transcript":
          console.log
          summary = data.transcript.text;
          break;
        default:
          console.log("this is bad");
      }
    });
  });
</script>

<div class="flex flex-col items-center">
  <div class="bg-black w-full flex justify-center mb-4">
    <img
      on:click={() => unshiftHeading({ name: "bob", phone: "1234567890", id: Math.random(), date: new Date().toLocaleString() })}
      src="/MnMLogoSmall.png"
      class="w-1/4 py-4"
    />
  </div>

  <div class="flex flex-row justify-center gap-20">
    <div>
      <div
        transition:fly={{ y: 100, duration: 1000 }}
        class="text-white-500 border border-slate-300 w-96 h-[80vh] max-h-[80vh] rounded-lg shadow-lg overflow-y-scroll"
      >
        <div class="p-6 flex flex-col gap-4">
          <input
            class="bg-white border outline-none text-grey border-gray-300 text-1xl
            hover:bg-transparent px-4 py-3 w-full placeholder:text-gray-500
            rounded-lg focus:border-gray-500 focus:shadow transition-all"
            placeholder="Search..."
            on:input={() => {
              clearTimeout(timeout);
              console.log("hi");
              isSearchLoading = true;
              timeout = setTimeout(() => {
                isSearchLoading = false;
                fetch(`http://localhost:8081/client/queryBySummary`, {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                  },
                  body: JSON.stringify({
                    search,
                  }),
                })
                  .then((res) => res.json())
                  .then((res) => {
                    console.log(res);
                    searchResults = res;
                  });
              }, 1000);
            }}
            bind:value={search}
          />
          {#if isSearchLoading}
            <div class="flex justify-center mt-16">
              <img in:fade src="/robotLogoLoad.gif" alt="" class="h-20 mb-8">
            </div>
          {:else}
            {#if searchResults.length === 0}
                <div class="flex flex-col justify-center items-center mt-8">
                  <div>No results found!</div>
                  <img in:fade src="/robotLogo.png" alt="" class="h-20 mb-8">
                </div>
            {/if}
            {#each searchResults as result}
              <div transition:fade>
                <a class="flex items-center gap-2 hover:underline hover:cursor-pointer" href={result.link}>
                  <span class="font-bold font-mono text-lg"
                    >{result.filename}</span
                  >
                  <img class="h-6 inline-block" src="/docxRob.png" />
                </a>
                <div>{result.summary ?? ""}</div>
              </div>
            {/each}
          {/if}
        </div>
      </div>
    </div>
    <div class="flex flex-col items-center justify-center">
      <div class="flex flex-col items-center justify-center w-96 relative">
          {#if summaryStatus === "done"}
          <div
            in:fade
            class="flex flex-col pt-8 px-4 items-center text-white-500 border h-[80vh] max-h-[80vh] overflow-y-scroll border-slate-300 w-full rounded-lg gap-4 shadow-lg"
          >
            <h2 class="flex justify-center text-4xl">Summary</h2>
            <p class="flex justify-center m-3">{summary}</p>
          </div>
          {/if}
          {#if summaryStatus !== "done"}
            <div in:fade class="contents">
              <img in:fade src="/robotLogoLoad.gif" alt="" class="mb-8">
            </div>
          {/if}
      </div>
    </div>
    <div>
      <div class="flex justify-center w-96">
        <div
          transition:fly={{ y: 100, duration: 1000 }}
          class="flex flex-col pt-8 px-4 text-white-500 border border-slate-300 w-full h-[80vh] overflow-y-scroll rounded-lg gap-4 shadow-lg"
        >
          <h2 class="flex justify-center text-4xl">Client Calls</h2>
          {#each headings as heading (heading.id)}
            <button animate:flip={{ duration: 400 }} transition:scale
              on:click={() => {
                currentPhone = formatPhoneNumber(heading.phone);
                console.log(currentPhone);
              }}
              class="bg-[#115099] rounded-lg py-2 m-2 text-white hover:bg-blue-950">
              {#if heading.name}
                <span class="mr-4">{heading.name}</span>
              {/if}
              <span>{heading.phone}</span>
              <span>{new Date(heading.date).toLocaleTimeString()}</span>
            </button>
          {/each}
        </div>
      </div>
    </div>

    <!--
<button
on:click={() => {
Notification.requestPermission();
}}
class={`bg-black border text-white border-black text-2xl
hover:bg-transparent hover:text-black px-5 py-3
rounded-lg drop-shadow-lg transition-all 
`}
>
<span class="mr-2">Rob</span><span>case 452</span>
</button>
-->
  </div>
</div>

// frontend/src/App.tsx
import { motion } from "framer-motion";
import { useEffect, useRef, useState } from "react";

const onMount = (func: () => void) => {
    const isMounted = useRef(false);
    useEffect(() => {
        if (!isMounted.current) {
            func();
            isMounted.current = true;
        }
    }, []);
};

const defaultSummary = `The Casey Anthony case is a high-profile criminal case that took place in the United States in 2011. 
Casey Anthony was a 25-year-old mother from Florida who was accused of murdering her two-year-old daughter, 
Caylee Anthony. The case received widespread media coverage and captivated the nation due to the gruesome nature 
of the crime and the conflicting evidence presented in court.`;

const client = "Casey Anthony";

function App() {
    const [summary, setSummary] = useState("");
    const [summaryStatus, setSummaryStatus] = useState("none");
    onMount(() => {
        const socket = new WebSocket("ws://localhost:1234"); socket.addEventListener("message", (event) => {
            const data = JSON.parse(event.data);
            console.log(data);
            switch (data.type) {
                case "newphonecall":
                    new Notification('New message from Rob', {
                        body: 'Case 452',
                    });
                    setSummaryStatus("loading");
                    break;
                case "summary":
                    setSummary(data.summary);
                    setSummaryStatus("done");
                    break;
            }
        })
    });
    return (
        <div className="flex flex-col items-center">
            <div className="bg-black w-full flex justify-center mb-4">
                <img src="/MnMLogoSmall.png" className="w-1/4 py-4" />
            </div>

            <div className="flex flex-col justify-center mb-4 gap-2">
                <h2>incoming calls:</h2>
                {/* when no call is received the text box should be replaced with a "no active calls" and when one is received but is loading, display a loading animation*/}
                <div className="flex justify-center">
                    {summaryStatus === "done" &&
                        <motion.div className='flex-row text-white-500 border-2 bg-slate-200 border-blue-200 w-96 h-auto rounded-lg gap-4'>
                            <h2 className='ml-4'>Client: {client}</h2>
                            <p className='mx-4 my-4'>{summary}</p>
                        </motion.div>
                    }
                    {summaryStatus === "loading" &&
                    <div className="w-min">
                        <svg className="animate-spin h-10 w-10 text-black" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                    </div>
                    }
                </div>
            </div>

            <button
                onClick={() => {
                    Notification.requestPermission()
                }}
                className={`bg-black border text-white border-black text-2xl
hover:bg-transparent hover:text-black px-5 py-3
rounded-lg drop-shadow-lg transition-all 
`}
            >
                <span className="mr-2">Rob</span><span>case 452</span>
            </button>
        </div>
    )
}

export default App
